import { v4 as uuidv4 } from 'uuid';
import { Project } from '../types';

const DEMO_IMAGES = [
  'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=640&h=360&fit=crop',
  'https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=640&h=360&fit=crop',
  'https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=640&h=360&fit=crop',
  'https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=640&h=360&fit=crop',
];

export function createDemoProjects(): Project[] {
  const now = new Date();
  const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
  const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);

  return [
    {
      id: uuidv4(),
      title: 'A Journey Above Dubai',
      originalPrompt: 'A luxury Emirates-style airplane flying over Dubai at sunset, with a businessman looking through the airplane window.',
      duration: 15,
      aspectRatio: '9:16',
      visualStyle: 'Cinematic',
      quality: 'High Quality',
      status: 'Completed',
      story: 'A breathtaking journey above the clouds. We begin with a sweeping view of Dubai bathed in golden sunset light. A luxury aircraft glides gracefully through the amber sky. Inside the pressurized cabin, warm light filters through oval windows. A distinguished passenger gazes out at the world below, lost in contemplation as the city transforms into a tapestry of light beneath him.',
      characters: [
        {
          id: uuidv4(),
          name: 'Daniel',
          age: 35,
          gender: 'Male',
          ethnicity: 'Indian',
          skinTone: 'Medium warm',
          hair: 'Short black hair, neatly styled',
          eyes: 'Dark brown',
          face: 'Strong jawline, short trimmed beard, warm expression',
          body: 'Athletic build, 5\'11"',
          clothing: 'Navy blue tailored business suit, crisp white shirt, black leather shoes',
          accessories: 'Silver wristwatch, wedding band',
          personality: 'Calm, confident, contemplative',
        },
      ],
      locations: [
        { id: uuidv4(), name: 'Dubai Skyline', description: 'Iconic Dubai skyline featuring Burj Khalifa and modern skyscrapers against golden sunset' },
        { id: uuidv4(), name: 'Luxury Aircraft Cabin', description: 'Premium first-class cabin with cream leather seats and warm ambient lighting' },
      ],
      scenes: [
        {
          id: uuidv4(), sceneNumber: 1, startTime: 0, duration: 3,
          description: 'Dubai skyline at golden sunset, establishing shot',
          cameraAngle: 'Wide aerial', cameraMovement: 'Drone Movement',
          characters: [], location: 'Dubai Skyline', objects: ['Skyscrapers', 'Sunset sky'],
          lighting: 'Golden hour warm light', weather: 'Clear', timeOfDay: 'Sunset',
          emotion: 'Awe, wonder', visualStyle: 'Cinematic',
          imagePrompt: 'Cinematic wide aerial shot of Dubai skyline at golden sunset', videoPrompt: 'Drone movement over Dubai skyline at sunset',
          status: 'completed', transition: 'Dissolve', generatedImage: DEMO_IMAGES[0],
        },
        {
          id: uuidv4(), sceneNumber: 2, startTime: 3, duration: 4,
          description: 'Luxury aircraft flying gracefully above Dubai',
          cameraAngle: 'Medium tracking', cameraMovement: 'Tracking Shot',
          characters: [], location: 'Sky above Dubai', objects: ['Aircraft', 'Clouds'],
          lighting: 'Warm sunset backlight', weather: 'Clear with light clouds', timeOfDay: 'Sunset',
          emotion: 'Elegance, freedom', visualStyle: 'Cinematic',
          imagePrompt: 'Cinematic tracking shot of luxury aircraft above Dubai', videoPrompt: 'Tracking shot following aircraft through clouds',
          status: 'completed', transition: 'Cut', generatedImage: DEMO_IMAGES[1],
        },
        {
          id: uuidv4(), sceneNumber: 3, startTime: 7, duration: 4,
          description: 'Interior of luxury airplane cabin',
          cameraAngle: 'Medium shot', cameraMovement: 'Slow Dolly In',
          characters: ['Daniel'], location: 'Luxury Aircraft Cabin', objects: ['Leather seat', 'Window'],
          lighting: 'Warm ambient cabin lighting', weather: 'N/A', timeOfDay: 'Sunset',
          emotion: 'Comfort, luxury', visualStyle: 'Cinematic',
          imagePrompt: 'Cinematic interior of luxury airplane cabin with warm lighting', videoPrompt: 'Slow dolly into luxury cabin interior',
          status: 'completed', transition: 'Dissolve', generatedImage: DEMO_IMAGES[2],
        },
        {
          id: uuidv4(), sceneNumber: 4, startTime: 11, duration: 4,
          description: 'Passenger looking through window at Dubai skyline',
          cameraAngle: 'Over-the-shoulder close-up', cameraMovement: 'Slow Zoom In',
          characters: ['Daniel'], location: 'Luxury Aircraft Cabin', objects: ['Window', 'Dubai skyline'],
          lighting: 'Golden light through window', weather: 'Clear', timeOfDay: 'Sunset',
          emotion: 'Contemplation, peace', visualStyle: 'Cinematic',
          imagePrompt: 'Cinematic over-shoulder shot of businessman looking through airplane window at sunset', videoPrompt: 'Slow zoom in on passenger looking out window',
          status: 'completed', transition: 'Fade', generatedImage: DEMO_IMAGES[3],
        },
      ],
      musicStyle: 'Cinematic',
      voiceover: 'Experience Dubai from above.',
      voiceGender: 'Male',
      voiceLanguage: 'English',
      finalVideo: 'ready',
      createdAt: twoDaysAgo.toISOString(),
      updatedAt: twoDaysAgo.toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Mountain Wilderness',
      originalPrompt: 'A solo hiker traversing a pristine mountain trail at dawn, with dramatic peaks and morning mist.',
      duration: 15,
      aspectRatio: '16:9',
      visualStyle: 'Photorealistic',
      quality: 'High Quality',
      status: 'Completed',
      story: 'Dawn breaks over untouched mountain wilderness. Morning mist rises from ancient valleys as golden light pierces through the peaks. A lone hiker traverses a winding trail, dwarfed by towering granite faces. The journey culminates at a breathtaking summit, where the world stretches endlessly below.',
      characters: [
        {
          id: uuidv4(),
          name: 'Sarah',
          age: 28,
          gender: 'Female',
          ethnicity: 'Caucasian',
          skinTone: 'Fair with warm undertones',
          hair: 'Long flowing auburn hair in a braid',
          eyes: 'Green',
          face: 'High cheekbones, natural beauty, determined expression',
          body: 'Athletic build, 5\'6"',
          clothing: 'Red hiking jacket, dark leggings, hiking boots',
          accessories: 'Backpack, trekking poles',
          personality: 'Adventurous, determined, peaceful',
        },
      ],
      locations: [
        { id: uuidv4(), name: 'Mountain Trail', description: 'Pristine alpine trail with wildflowers and granite boulders' },
        { id: uuidv4(), name: 'Summit View', description: 'Panoramic mountain summit with 360-degree views' },
      ],
      scenes: [
        {
          id: uuidv4(), sceneNumber: 1, startTime: 0, duration: 4,
          description: 'Dawn breaking over mountain peaks with morning mist',
          cameraAngle: 'Wide establishing', cameraMovement: 'Slow Zoom In',
          characters: [], location: 'Mountain Wilderness', objects: ['Peaks', 'Mist', 'Sunrise'],
          lighting: 'First light golden', weather: 'Clear with morning mist', timeOfDay: 'Dawn',
          emotion: 'Serenity, anticipation', visualStyle: 'Photorealistic',
          imagePrompt: 'Photorealistic wide shot of mountain peaks at dawn with morning mist', videoPrompt: 'Slow zoom into mountain peaks at dawn',
          status: 'completed', transition: 'Dissolve', generatedImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&h=360&fit=crop',
        },
        {
          id: uuidv4(), sceneNumber: 2, startTime: 4, duration: 4,
          description: 'Hiker on mountain trail surrounded by wildflowers',
          cameraAngle: 'Medium shot', cameraMovement: 'Tracking Shot',
          characters: ['Sarah'], location: 'Mountain Trail', objects: ['Trail', 'Wildflowers', 'Backpack'],
          lighting: 'Soft morning light', weather: 'Clear', timeOfDay: 'Morning',
          emotion: 'Determination, freedom', visualStyle: 'Photorealistic',
          imagePrompt: 'Photorealistic tracking shot of female hiker on mountain trail', videoPrompt: 'Tracking shot following hiker along trail',
          status: 'completed', transition: 'Cut', generatedImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=640&h=360&fit=crop',
        },
        {
          id: uuidv4(), sceneNumber: 3, startTime: 8, duration: 3,
          description: 'Close-up of hiker reaching summit, wind in hair',
          cameraAngle: 'Close-up', cameraMovement: 'Handheld',
          characters: ['Sarah'], location: 'Summit View', objects: ['Summit marker', 'Wind'],
          lighting: 'Bright natural light', weather: 'Light breeze', timeOfDay: 'Morning',
          emotion: 'Triumph, joy', visualStyle: 'Photorealistic',
          imagePrompt: 'Photorealistic close-up of female hiker at mountain summit', videoPrompt: 'Handheld close-up of hiker at summit',
          status: 'completed', transition: 'Dissolve', generatedImage: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=640&h=360&fit=crop',
        },
        {
          id: uuidv4(), sceneNumber: 4, startTime: 11, duration: 4,
          description: 'Panoramic view from summit, hiker small against vast landscape',
          cameraAngle: 'Ultra wide', cameraMovement: 'Slow Zoom Out',
          characters: ['Sarah'], location: 'Summit View', objects: ['Mountains', 'Valleys', 'Sky'],
          lighting: 'Golden morning light', weather: 'Clear', timeOfDay: 'Morning',
          emotion: 'Awe, insignificance', visualStyle: 'Photorealistic',
          imagePrompt: 'Photorealistic ultra wide panoramic from mountain summit', videoPrompt: 'Slow zoom out revealing vast mountain panorama',
          status: 'completed', transition: 'Fade', generatedImage: 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=640&h=360&fit=crop',
        },
      ],
      musicStyle: 'Inspirational',
      voiceover: '',
      voiceGender: 'Female',
      voiceLanguage: 'English',
      finalVideo: 'ready',
      createdAt: yesterday.toISOString(),
      updatedAt: yesterday.toISOString(),
    },
  ];
}
